### ISSUE TITLE
Error about QOpenGLShader

### ISSUE THREAD

**Issue by lizhengning** [tatsy/LightField#3]
After build the project, it runs with error:
QOpenGLShader::compile(Vertex): ERROR: 0:1: '' :  version '150' is not supported
ERROR: 0:6: 'smooth' : syntax error: syntax error
I think maybe its about the OpenGL version

**Comment by tatsy** [comment]
Check the OpenGL support of your platform.
GLSL v1.5 (and also OpenGL 3.3) is supported by very old hardware (and also by new ones).
So I hardly believe your platform does not support this.

I guess your platform is MacOSX. If so, you need a special care to use OpenGL whose version is higher than 2.0.
The following code helps.
https://github.com/tatsy/qt5-shadow-maps/blob/master/sources/appmain.cpp#L9

**Comment by lizhengning** [comment]
Thanks，everything is ok now, and I load the images from stanford, the screen is black and an info shows: light field texture is binded!!

**Comment by tatsy** [comment]
Actually, I have not tested this program on MacOSX, so I am not sure about this program correctly works on it.
The typical problem of MacOS is its Letina display. It often causes the problem with OpenGL.
I am sure that the problem can be fixed if all the things are correctly set, but it would be a bit complicated.
So, if you are not an expert of OpenGL on MacOS, I strongly recommend that you first test this program on the other platform.

**Comment by lizhengning** [comment]
followed your suggestion, I run on ubuntu 16.04, and there is still someproblem
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
QOpenGLWidget: Failed to create context

**Comment by ultra-sonic** [comment]
what hardware are you running on? Sounds like Intel IRIS GPU to me which is
total crap for OpenGL development. I also had these issues.

**Comment by lizhengning** [comment]
I have a GTX-1080

**Comment by tatsy** [comment]
While I have no much time to elaborate this problem, but I guess the image size is another important factor. 

Typically, the size of power of 2 is more preferable to the majority of hardware. 

I think the memory size of GTX-1080 is enough for this program, but the small memory size of Intel IRIS can be problematic (I am not very sure).

Anyway, I understand your problem and I check it in the near future.
Thank you for your information.
